// backend の呼び出し先カタログ。**フロントが叩ける先はここに書かれたものだけ。**
//
// なぜ1つの表にするか: 呼び出しが散らばっていると、どこを叩いているかを
// 知るのに全ソースを読み解くしかない。読み解きは精度を要求するので、
// 読み違えれば黙って通る。表にすれば、突き合わせは読み解きではなく列挙になる。
//
// **このファイルの書き方は機械が縛っている**（backend/ux_verification/ui_api_closure.py）。
// 1項目1行、method と path はシングルクォートのリテラルのみ。変数・連結・
// テンプレートリテラルは書けない。書けば FAIL になる。
//
// `{name}` はパスパラメータ。client.js の apiUrl が params から埋める。
// クエリ文字列はここに書かない（query オプションで渡す）。

export const ENDPOINTS = {
  deletePipelineDictionary: { method: 'DELETE', path: '/api/pipeline/dictionary/{entry_id}' },
  getCollaborationJournal: { method: 'GET', path: '/api/collaboration/journal' },
  getDashboardHealth: { method: 'GET', path: '/api/dashboard/health' },
  getDirectorEvolution: { method: 'GET', path: '/api/director/evolution' },
  getDirectorState: { method: 'GET', path: '/api/director/state' },
  getDirectorTasks: { method: 'GET', path: '/api/director/tasks/{task_id}' },
  getPipelineDictionary: { method: 'GET', path: '/api/pipeline/dictionary' },
  getPipelineOpenFolder: { method: 'GET', path: '/api/pipeline/open-folder' },
  getPipelineProofreadingExport: { method: 'GET', path: '/api/pipeline/proofreading/export/{export_format}' },
  getPipelineProofreadingResult: { method: 'GET', path: '/api/pipeline/proofreading/result' },
  getPipelineProofreadingStatus: { method: 'GET', path: '/api/pipeline/proofreading/status' },
  getPipelineQualityGateStatus: { method: 'GET', path: '/api/pipeline/quality-gate/status' },
  getPipelineStatus: { method: 'GET', path: '/api/pipeline/status' },
  getPipelineStream: { method: 'GET', path: '/api/pipeline/stream/{video_type}' },
  getPipelineTranscriptionModels: { method: 'GET', path: '/api/pipeline/transcription/models' },
  getPipelineTranscriptionSegments: { method: 'GET', path: '/api/pipeline/transcription/segments' },
  getPipelineTranscriptionStatus: { method: 'GET', path: '/api/pipeline/transcription/status' },
  getPipelineVideos: { method: 'GET', path: '/api/pipeline/videos' },
  getSegments: { method: 'GET', path: '/api/segments' },
  getSettings: { method: 'GET', path: '/api/settings' },
  getSmartcutAllCandidates: { method: 'GET', path: '/api/smartcut/all-candidates' },
  getStatus: { method: 'GET', path: '/api/status' },
  getTranscribeStatus: { method: 'GET', path: '/api/transcribe/status' },
  getUsageDashboard: { method: 'GET', path: '/api/usage/dashboard' },
  getUsageGovernance: { method: 'GET', path: '/api/usage/governance' },
  getUsageRetryBudget: { method: 'GET', path: '/api/usage/retry-budget' },
  getUsageSwitchHistory: { method: 'GET', path: '/api/usage/switch-history' },
  getV1ThemesCurrentActive: { method: 'GET', path: '/api/v1/themes/current/active' },
  getVideo: { method: 'GET', path: '/api/video' },
  postCollaborationFeedback: { method: 'POST', path: '/api/collaboration/feedback' },
  postCollaborationJournal: { method: 'POST', path: '/api/collaboration/journal' },
  postCouncilDecision: { method: 'POST', path: '/api/council/decision' },
  postCouncilSession: { method: 'POST', path: '/api/council/session' },
  postDirectorAnalyzeResources: { method: 'POST', path: '/api/director/analyze-resources' },
  postDirectorAnalyzeScript: { method: 'POST', path: '/api/director/analyze-script' },
  postDirectorBatchGenerate: { method: 'POST', path: '/api/director/batch-generate' },
  postDirectorChat: { method: 'POST', path: '/api/director/chat' },
  postDirectorGenerateImageAsync: { method: 'POST', path: '/api/director/generate-image-async' },
  postDirectorGenerateReport: { method: 'POST', path: '/api/director/generate-report' },
  postDirectorPlanStoryboard: { method: 'POST', path: '/api/director/plan-storyboard' },
  postDirectorQualityScore: { method: 'POST', path: '/api/director/quality-score' },
  postDirectorState: { method: 'POST', path: '/api/director/state' },
  postDirectorVerifyQuality: { method: 'POST', path: '/api/director/verify-quality' },
  postPipelineDictionary: { method: 'POST', path: '/api/pipeline/dictionary' },
  postPipelineProofreadingApprove: { method: 'POST', path: '/api/pipeline/proofreading/approve' },
  postPipelineProofreadingApproveAll: { method: 'POST', path: '/api/pipeline/proofreading/approve-all' },
  postPipelineProofreadingReject: { method: 'POST', path: '/api/pipeline/proofreading/reject' },
  postPipelineProofreadingRejectAll: { method: 'POST', path: '/api/pipeline/proofreading/reject-all' },
  postPipelineProofreadingSkip: { method: 'POST', path: '/api/pipeline/proofreading/skip' },
  postPipelineQualityGateImprove: { method: 'POST', path: '/api/pipeline/quality-gate/improve' },
  postPipelineStart: { method: 'POST', path: '/api/pipeline/start' },
  postPipelineTranscriptionModel: { method: 'POST', path: '/api/pipeline/transcription/model' },
  postPipelineVideosMetadata: { method: 'POST', path: '/api/pipeline/videos/metadata' },
  postPipelineVideosValidate: { method: 'POST', path: '/api/pipeline/videos/validate' },
  postQualityApplySuggestion: { method: 'POST', path: '/api/quality/apply-suggestion' },
  postQualityDecisionQuick: { method: 'POST', path: '/api/quality/decision/quick' },
  postQualityReviewApprove: { method: 'POST', path: '/api/quality/review/approve' },
  postQualityUndoSuggestion: { method: 'POST', path: '/api/quality/undo-suggestion' },
  postRender: { method: 'POST', path: '/api/render' },
  postRenderStart: { method: 'POST', path: '/api/render/start' },
  postRhythmSplit: { method: 'POST', path: '/api/rhythm/split' },
  postSegments: { method: 'POST', path: '/api/segments' },
  postSettingsIdentity: { method: 'POST', path: '/api/settings/identity' },
  postSettingsReset: { method: 'POST', path: '/api/settings/reset' },
  postSettingsVideo: { method: 'POST', path: '/api/settings/video' },
  postShortsCandidates: { method: 'POST', path: '/api/shorts/candidates' },
  postShortsRender: { method: 'POST', path: '/api/shorts/render' },
  postSmartcutFinalize: { method: 'POST', path: '/api/smartcut/finalize' },
  postSmartcutInit: { method: 'POST', path: '/api/smartcut/init' },
  postSmartcutLock: { method: 'POST', path: '/api/smartcut/lock' },
  postSmartcutRecommend: { method: 'POST', path: '/api/smartcut/recommend' },
  postSmartcutUnlock: { method: 'POST', path: '/api/smartcut/unlock' },
  postThumbnailSelect: { method: 'POST', path: '/api/thumbnail/select' },
  postTranscribe: { method: 'POST', path: '/api/transcribe' },
  postV1ThemesApply: { method: 'POST', path: '/api/v1/themes/apply' },
  postV1ThemesRecommend: { method: 'POST', path: '/api/v1/themes/recommend' },
  postYoutubeApplyHook: { method: 'POST', path: '/api/youtube/apply-hook' },
  postYoutubeImproveHook: { method: 'POST', path: '/api/youtube/improve-hook' },
  postYoutubeOptimize: { method: 'POST', path: '/api/youtube/optimize' },
  postYoutubePrePlan: { method: 'POST', path: '/api/youtube/pre-plan' },
  putPipelineTranscriptionSegments: { method: 'PUT', path: '/api/pipeline/transcription/segments/{segment_id}' },
  wsPipeline: { method: 'WEBSOCKET', path: '/api/pipeline/ws/pipeline' },
};
